### ISSUE TITLE
Could you update this mod to have the option to customize the respawn time?

### ISSUE THREAD

**Issue by GamerGoddessDin** [JavidPack/ShorterRespawn#1]
Or alternatively tell me what unit the respawn timer property this modifies uses so I can more easily make my own fork that has some limited customization.

**Comment by JavidPack** [comment]
I will once tmod supports modconfigs, but the easiest customization is changing

player.respawnTimer = (int)(player.respawnTimer * .75);

the .75 means 75% of the original value, you can change this to .25 to make respawn happen 4 times as fast as normal.

**Comment by JavidPack** [comment]
v1.0 for tModLoader 0.11.2.2 has this now.
